---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tenant-apiserver
  name: tenant-apiserver
  namespace: metal-control-plane
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "2113"
    port: 2113
    protocol: TCP
    targetPort: 2112
  selector:
    app: tenant-apiserver
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-apiserver
  namespace: metal-control-plane
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tenant-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
      labels:
        app: tenant-apiserver
    spec:
      containers:
      - env:
        - name: TENANT_APISERVER_GRPC_SERVER_ENDPOINT
          value: "0.0.0.0:8080"
        - name: TENANT_APISERVER_PG_HOST
          value: masterdata-db
        - name: TENANT_APISERVER_PG_DBNAME
          value: masterdata
        - name: TENANT_APISERVER_PG_PASSWORD
          value: change-me
        - name: TENANT_APISERVER_PG_PORT
          value: "5432"
        - name: TENANT_APISERVER_PG_USER
          value: postgres
        image: ghcr.io/metal-stack/tenant-apiserver:latest
        imagePullPolicy: Always
        name: tenant-apiserver
        command:
          - /server
          - postgres
        ports:
        - containerPort: 2112
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
